name: car_catalog
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.1.0

  image_picker: ^0.8.5


  json_annotation: ^4.4.0

  #  firebase
  firebase_core: ^1.14.0
  cloud_firestore: ^3.1.11
  firebase_storage: ^10.2.11

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  json_serializable: ^6.1.5

flutter:
  uses-material-design: true
