// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo2XNRyM29U-U52_Yg1GGsFuPonBSfw18',
    appId: '1:208449019232:android:cb7936c98072565b9a9205',
    messagingSenderId: '208449019232',
    projectId: 'car-catalog-80840',
    storageBucket: 'car-catalog-80840.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbDopdOflQB6sFZ4CbF8r2KKJ5evKoTf8',
    appId: '1:208449019232:ios:7c500369400ed8909a9205',
    messagingSenderId: '208449019232',
    projectId: 'car-catalog-80840',
    storageBucket: 'car-catalog-80840.appspot.com',
    iosClientId: '208449019232-9kpr4tohoeej7pjik9l5dlrje0suksmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.carCatalog',
  );
}
